#!/usr/bin/env bash
# Double the number of webservers

# update local repository
sudo apt-get update -y

# install nginx
sudo apt-get install nginx -y

# write content to index.html
touch index.html
echo "Hello World!" > index.html
sudo mv index.html /var/www/html

touch 404.html
echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html

echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	add_header X-Served-By $HOSTNAME;

	root /var/www/html;
	index index.html;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
	
	error_page 404 /404.html;
	location /404 {
		root /etc/nginx/html;
		internal;
	}
}" > default
sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
