#!/usr/bin/env bash
# Double the number of webservers

# update local repository
apt-get update

# install nginx
apt-get install nginx -y

# write content to index.html
mkdir -p /var/www/html
touch index.html
echo "Hello World!" > index.html
mv index.html /var/www/html

touch 404.html
echo "Ceci n'est pas une page" > 404.html
mv 404.html /var/www/html

printf %s "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	add_header X-Served-By $HOSTNAME;
	root /var/www/html;
	index index.html index.htm;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
	error_page 404 /404.html;
	location /404 {
		root /etc/www/html;
		internal;
	}
}" > /etc/nginx/sites-available/default

sudo service nginx restart

