#!/usr/bin/env bash

# update local repository
sudo apt-get update -y

# install nginx
sudo apt-get install nginx -y

# back up default nginx server conf
mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# write content to index.html
echo "Hello World!" > index.html
sudo mv index.html /var/www/html

echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html
sudo chown $USER:$USER /var/www/html/*

echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	add_header X-Served-By $HOSTNAME;

	root /var/www/html;
	index index.html;
	location /redirect {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
	
	error_page 404 /404.html;
	location =404.html {
		internal;
	}
}" > default
sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
